# Generated by Django 5.1.5 on 2025-01-21 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0003_alter_assignment_course_alter_certificate_course_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_role',
            field=models.CharField(choices=[('student', 'student'), ('teacher', 'teacher')], max_length=64),
        ),
    ]
